# Generated by Django 2.1.7 on 2019-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_remove_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
