# Generated by Django 2.1.7 on 2019-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(default='', max_length=170),
        ),
    ]
