# Generated by Django 2.1.7 on 2019-02-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0005_auto_20190224_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('locale', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='', max_length=170)),
            ],
        ),
        migrations.DeleteModel(
            name='SeoTag',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='locale',
        ),
        migrations.AddField(
            model_name='page',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='product.Seo'),
        ),
    ]
