# Generated by Django 2.1.7 on 2019-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0007_auto_20190224_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
