# Generated by Django 2.1.7 on 2019-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0009_auto_20190224_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
