# Generated by Django 2.1.7 on 2019-02-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0010_auto_20190224_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='product.Contact'),
        ),
    ]
