# Generated by Django 2.1.7 on 2019-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0011_page_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='components',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('navs', 'navs'), ('work.html', 'work.html'),
                         ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'), ('slide.html', 'slide.html'),
                         ('content.html', 'content.html')], default='default.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('navs', 'navs'), ('work.html', 'work.html'),
                         ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'), ('slide.html', 'slide.html'),
                         ('content.html', 'content.html')], default='default.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('navs', 'navs'), ('work.html', 'work.html'),
                         ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'), ('slide.html', 'slide.html'),
                         ('content.html', 'content.html')], default='default.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('navs', 'navs'), ('work.html', 'work.html'),
                         ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'), ('slide.html', 'slide.html'),
                         ('content.html', 'content.html')], default='default.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='slider',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('navs', 'navs'), ('work.html', 'work.html'),
                         ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'), ('slide.html', 'slide.html'),
                         ('content.html', 'content.html')], default='default.html', max_length=20),
        ),
        migrations.AddField(
            model_name='footer',
            name='links',
            field=models.ManyToManyField(to='product.Link'),
        ),
    ]
