# Generated by Django 2.1.7 on 2019-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0014_remove_link_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AlterField(
            model_name='components',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('carousel.html', 'carousel.html'), ('navs', 'navs'),
                         ('work.html', 'work.html'), ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'),
                         ('slide.html', 'slide.html'), ('content.html', 'content.html')], default='default.html',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('carousel.html', 'carousel.html'), ('navs', 'navs'),
                         ('work.html', 'work.html'), ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'),
                         ('slide.html', 'slide.html'), ('content.html', 'content.html')], default='default.html',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('carousel.html', 'carousel.html'), ('navs', 'navs'),
                         ('work.html', 'work.html'), ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'),
                         ('slide.html', 'slide.html'), ('content.html', 'content.html')], default='default.html',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('carousel.html', 'carousel.html'), ('navs', 'navs'),
                         ('work.html', 'work.html'), ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'),
                         ('slide.html', 'slide.html'), ('content.html', 'content.html')], default='default.html',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='slider',
            name='item',
            field=models.ManyToManyField(to='product.SliderItem'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='template',
            field=models.CharField(
                choices=[('navbar.html', 'navbar.html'), ('link.html', 'link.html'), ('index.html', 'index.html'),
                         ('default.html', 'default.html'), ('product.html', 'product.html'),
                         ('nav-item.html', 'nav-item.html'), ('nav-dropdown.html', 'nav-dropdown.html'),
                         ('about.html', 'about.html'), ('base.html', 'base.html'), ('contact.html', 'contact.html'),
                         ('pricing.html', 'pricing.html'), ('carousel.html', 'carousel.html'), ('navs', 'navs'),
                         ('work.html', 'work.html'), ('dynamic.html', 'dynamic.html'), ('footer.html', 'footer.html'),
                         ('slide.html', 'slide.html'), ('content.html', 'content.html')], default='default.html',
                max_length=20),
        ),
        migrations.AddField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(to='product.Image'),
        ),
    ]
