# Generated by Django 2.1.7 on 2019-02-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0015_auto_20190224_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='item',
        ),
        migrations.AddField(
            model_name='slider',
            name='mainImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img',
                                    to='product.Image'),
        ),
    ]
