# Generated by Django 2.1.7 on 2019-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0016_auto_20190224_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='item',
            field=models.ManyToManyField(to='product.SliderItem'),
        ),
    ]
